public with sharing class Test {
    private String campoUno;
    private String campoDos;

    public String getCampoUno() {
        return campoUno;
    }

    public void setCampoUno(String campoUno) {
        this.campoUno = campoUno;
    }

    public String getCampoDos() {
        return campoDos;
    }

    public void setCampoDos(String campoDos) {
        this.campoDos = campoDos;
    }
}
