name: Org Monitoring
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  backup-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - run: npm install --global @salesforce/cli && sf plugins install sfdx-hardis
      - name: JWT auth
        run: sf hardis auth login
        env:
          SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
          SF_JWT_KEY: ${{ secrets.SF_JWT_KEY }}
      - name: Backup + audit trail
        run: sf hardis org monitor backup

  backup-prod:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - run: npm install --global @salesforce/cli && sf plugins install sfdx-hardis
      - name: JWT auth
        run: sf hardis auth login
        env:
          SF_CLIENT_ID: ${{ secrets.SF_CLIENT_ID }}
          SF_JWT_KEY: ${{ secrets.SF_JWT_KEY }}
      - name: Backup + audit trail
        run: sf hardis org monitor backup
